---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeflow-netapp-dataops
  namespace: admin # Replace with desired Kubeflow namespace
subjects:
- kind: ServiceAccount
  name: default-editor
  namespace: admin # Replace with desired Kubeflow namespace
roleRef:
  kind: ClusterRole
  name: netapp-dataops
  apiGroup: rbac.authorization.k8s.io