apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: digits-recognizer
  namespace: kubeflow-user-example-com
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  predictor:
    tensorflow:
      storageUri: pvc://digits-model