---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: airflow-netapp-dataops
  namespace: airflow # Replace with desired Airflow namespace
subjects:
- kind: ServiceAccount
  name: default
  namespace: airflow # Replace with desired Airflow namespace
roleRef:
  kind: ClusterRole
  name: netapp-dataops
  apiGroup: rbac.authorization.k8s.io