apiVersion: v1
kind: Service
metadata:
  labels:
    app: chatter-ollama-app
  name: chatter-ollama-srv
  namespace: chatter-app
spec:
  ports:
  - name: http
    port: 11434
    targetPort: 11434
    protocol: TCP
  selector:
    app: chatter-ollama-app
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatter-pvc-ollama
  namespace: chatter-app
spec:
  resources:
    requests:
      storage: CHANGE_ME
  storageClassName: CHANGE_ME
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: chatter-ollama-app
  name: chatter-ollama-ss
  namespace: chatter-app
spec:
  serviceName: 'chatter-ollama-srv'
  replicas: 1
  selector:
    matchLabels:
      app: chatter-ollama-app
  template:
    metadata:
      labels:
        app: chatter-ollama-app
    spec:
      containers:
      - image: curtisab/chatter-ollama:0.1.34
        name: chatter-ollama-app
        volumeMounts:
        - mountPath: /root/.ollama
          name: ollama-pvc
        resources: 
          requests: 
            cpu: "3"
            memory: 18G
          limits: 
            cpu: "4"
            memory: 18G
      volumes:
      - name: ollama-pvc
        persistentVolumeClaim: 
          claimName: CHANGE_ME
      hostAliases:
      - ip: 172.67.187.229
        hostnames:
        - "registry.ollama.ai" 