apiVersion: v1
kind: Service
metadata:
  labels:
    app: chatter-ollama-app
  name: chatter-ollama-srv
  namespace: chatter-app
spec:
  ports:
  - name: http
    port: 11434
    targetPort: 11434
    protocol: TCP
  selector:
    app: chatter-ollama-app
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: chatter-ollama-app
  name: chatter-ollama-ss
  namespace: chatter-app
spec:
  serviceName: 'chatter-ollama-srv'
  replicas: 1
  selector:
    matchLabels:
      app: chatter-ollama-app
  template:
    metadata:
      labels:
        app: chatter-ollama-app
    spec:
      containers:
      - image: curtisab/chatter-ollama:0.1.34
        name: chatter-ollama-app
        resources: 
          requests: 
            cpu: "2"
            memory: "18GB"
          limits: 
            cpu: "2"
            memory: "18GB"