apiVersion: v1
kind: Secret
metadata:
  name: c1-svmai-backend-secret
  namespace: trident
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: Netapp1!
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: c1-svmai-nas-backend
  namespace: trident
spec:
  version: 1
  backendName: c1-svmai-ontap-nas-backend
  storageDriverName: ontap-nas
  replicationPolicy: MirrorAllSnapshots
  managementLIF: 192.168.0.101
  dataLIF: 192.168.0.31
  svm: svmai
  credentials:
    name: c1-svmai-backend-secret
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: c1-svmai-san-backend
  namespace: trident
spec:
  version: 1
  backendName: c1-svmai-ontap-san-backend
  replicationPolicy: MirrorAllSnapshots
  storageDriverName: ontap-san
  managementLIF: 192.168.0.101
  dataLIF: 192.168.0.32
  svm: svmai
  credentials:
    name: c1-svmai-backend-secret
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: c1-svmai-nas-basic
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.trident.netapp.io
parameters:
  storagePools: "c1-svmai-ontap-nas-backend:.*"
  fsType: nfs 
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: c1-svmai-san-basic
provisioner: csi.trident.netapp.io
parameters:
  storagePools: "c1-svmai-ontap-san-backend:.*"