apiVersion: v1
kind: Secret
metadata:
  name: ontap-admin-account
  namespace: admin # Replace with desired Kubeflow namespace
data: 
  username: <your_ontap_cluster_or_svm_admin_username_encoded_in_base64>
  password: <your_ontap_cluster_or_svm_admin_password_encoded_in_base64>